version: "3.9"

services:
  redis:
    image: redis
    container_name: slugfeast-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--save", "500", "1"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
