-- AlterTable
ALTER TABLE "blockTimeStamps" ALTER COLUMN "tokenDeployedsTimestamp" SET DATA TYPE BIGINT,
ALTER COLUMN "tokenDeployedsLastId" SET DEFAULT '',
ALTER COLUMN "tokenDeployedsLastId" SET DATA TYPE TEXT,
ALTER COLUMN "tokenGraduatedsTimestamp" SET DATA TYPE BIGINT,
ALTER COLUMN "tokenGraduatedsLastId" SET DEFAULT '',
ALTER COLUMN "tokenGraduatedsLastId" SET DATA TYPE TEXT,
ALTER COLUMN "tokenBoughtsTimestamp" SET DATA TYPE BIGINT,
ALTER COLUMN "tokenBoughtsLastId" SET DEFAULT '',
ALTER COLUMN "tokenBoughtsLastId" SET DATA TYPE TEXT,
ALTER COLUMN "tokenSoldsTimestamp" SET DATA TYPE BIGINT,
ALTER COLUMN "tokenSoldsLastId" SET DEFAULT '',
ALTER COLUMN "tokenSoldsLastId" SET DATA TYPE TEXT,
ALTER COLUMN "poolcreatedsTimestamp" SET DATA TYPE BIGINT,
ALTER COLUMN "poolcreatedsLastId" SET DEFAULT '',
ALTER COLUMN "poolcreatedsLastId" SET DATA TYPE TEXT,
ALTER COLUMN "tokencreatedLastId" SET DEFAULT '',
ALTER COLUMN "tokencreatedLastId" SET DATA TYPE TEXT,
ALTER COLUMN "tokencreatedsTimestamp" SET DATA TYPE BIGINT;
